@rifaterdemsahin ‚ûú /workspaces/PipelineAutomation/6_üî£_Symbols/3_Pipelines (main) $ tkn pipelinerun logs echo-date-pipeline-run -f
Error retrieving pipeline for pipelinerun default/echo-date-pipeline-run: error when getting Pipeline for PipelineRun echo-date-pipeline-run: tekton client cannot get pipeline echo-date-pipeline from local cluster: pipelines.tekton.dev "echo-date-pipeline" not found
@rifaterdemsahin ‚ûú /workspaces/PipelineAutomation/6_üî£_Symbols/3_Pipelines (main) $ 


---

It looks like the Tekton client is unable to find the `echo-date-pipeline`. Here are a few steps to troubleshoot this issue:

1. **Verify the Pipeline Creation**:
   Ensure that the pipeline was created successfully. You can check the pipelines in your cluster with:
   ```bash
   kubectl get pipelines
   ```
@rifaterdemsahin ‚ûú /workspaces/PipelineAutomation/6_üî£_Symbols/3_Pipelines (main) $    kubectl get pipelines
NAME                 AGE
echo-date-pipeline   12m

2. **Check the Namespace**:
   Make sure you are in the correct namespace where the pipeline was created. If it was created in a different namespace, specify the namespace in your command:
   ```bash
   tkn pipelinerun logs echo-date-pipeline-run -f -n <namespace>
   ```


@rifaterdemsahin ‚ûú /workspaces/PipelineAutomation/6_üî£_Symbols/3_Pipelines (main) $ tkn pipelinerun logs echo-date-pipeline-run -f
Error retrieving pipeline for pipelinerun default/echo-date-pipeline-run: error when getting Pipeline for PipelineRun echo-date-pipeline-run: tekton client cannot get pipeline echo-date-pipeline from local cluster: pipelines.tekton.dev "echo-date-pipeline" not found
@rifaterdemsahin ‚ûú /workspaces/PipelineAutomation/6_üî£_Symbols/3_Pipelines (main) $ 

3. **Inspect Pipeline YAML**:
   Double-check the YAML file used to create the pipeline to ensure there are no errors or typos.

4. **PipelineRun Status**:
   Check the status of the PipelineRun to see if there are any errors:
   ```bash
   tkn pipelinerun describe echo-date-pipeline-run
   ```

@rifaterdemsahin ‚ûú /workspaces/PipelineAutomation/6_üî£_Symbols/3_Pipelines (main) $    tkn pipelinerun describe echo-date-pipeline-run
Name:              echo-date-pipeline-run
Namespace:         default
Pipeline Ref:      echo-date-pipeline
Service Account:   default
Labels:
 tekton.dev/pipeline=echo-date-pipeline

üå°Ô∏è  Status

STARTED          DURATION   STATUS
13 minutes ago   0s         Failed(CouldntGetPipeline)

üíå Message

Error retrieving pipeline for pipelinerun default/echo-date-pipeline-run: error when getting Pipeline for PipelineRun echo-date-pipeline-run: tekton client cannot get pipeline echo-date-pipeline from local cluster: pipelines.tekton.dev "echo-date-pipeline" not found

‚è±  Timeouts
 Pipeline:   1h0m0s
@rifaterdemsahin ‚ûú /workspaces/PipelineAutomation/6_üî£_Symbols/3_Pipelines (main) $ 

5. **Tekton Controller Logs**:
   Inspect the logs of the Tekton controller for any errors or warnings:
   ```bash
   kubectl logs -l app=tekton-pipelines-controller -n tekton-pipelines
   ```

If the pipeline is still not found, you might need to recreate it or check for any issues in the Tekton installation[1](https://stackoverflow.com/questions/77690711/tekton-cli-in-pod-cannot-find-existing-pipeline)[2](https://github.com/tektoncd/pipeline/issues/5804).

Let me know if you need further assistance! üòä


rifaterdemsahin ‚ûú /workspaces/PipelineAutomation/6_üî£_Symbols/3_Pipelines (main) $    kubectl logs -l app=tekton-pipelines-controller -n tekton-pipelines
{"severity":"info","timestamp":"2025-03-27T11:37:59.641Z","logger":"tekton-pipelines-controller","caller":"leaderelection/context.go:156","message":"\"tekton-pipelines-controller-59f45c5dcd-48kzn_03b13752-afc0-4fbb-ba28-dd3b40f2eafe\" has started leading \"tekton-pipelines-controller.github.com.tektoncd.pipeline.pkg.reconciler.taskrun.reconciler.00-of-01\"","commit":"1122e76"}
{"severity":"info","timestamp":"2025-03-27T11:37:59.641Z","logger":"tekton-pipelines-controller","caller":"leaderelection/context.go:156","message":"\"tekton-pipelines-controller-59f45c5dcd-48kzn_2805f65e-192f-438a-a560-5b4467225694\" has started leading \"tekton-pipelines-controller.github.com.tektoncd.pipeline.pkg.reconciler.resolutionrequest.reconciler.00-of-01\"","commit":"1122e76"}
{"severity":"info","timestamp":"2025-03-27T11:41:20.662Z","logger":"tekton-pipelines-controller.event-broadcaster","caller":"record/event.go:377","message":"Event(v1.ObjectReference{Kind:\"PipelineRun\", Namespace:\"default\", Name:\"echo-date-pipeline-run\", UID:\"0d90692a-32ba-4325-beba-367da1c28dcb\", APIVersion:\"tekton.dev/v1\", ResourceVersion:\"1906\", FieldPath:\"\"}): type: 'Normal' reason: 'Started' ","commit":"1122e76"}
{"severity":"error","timestamp":"2025-03-27T11:41:20.669Z","logger":"tekton-pipelines-controller","caller":"pipelinerun/pipelinerun.go:438","message":"Failed to determine Pipeline spec to use for pipelinerun echo-date-pipeline-run: error when getting Pipeline for PipelineRun echo-date-pipeline-run: tekton client cannot get pipeline echo-date-pipeline from local cluster: pipelines.tekton.dev \"echo-date-pipeline\" not found","commit":"1122e76","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"36dddc4d-7bf8-48f4-925f-bf291578206e","knative.dev/key":"default/echo-date-pipeline-run","stacktrace":"github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun.(*Reconciler).reconcile\n\tgithub.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/pipelinerun.go:438\ngithub.com/tektoncd/pipeline/pkg/reconciler/pipelinerun.(*Reconciler).ReconcileKind\n\tgithub.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/pipelinerun.go:266\ngithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1/pipelinerun.(*reconcilerImpl).Reconcile\n\tgithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1/pipelinerun/reconciler.go:236\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20250117084104-c43477f0052b/controller/controller.go:540\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20250117084104-c43477f0052b/controller/controller.go:489"}
{"severity":"error","timestamp":"2025-03-27T11:41:20.670Z","logger":"tekton-pipelines-controller","caller":"pipelinerun/pipelinerun.go:267","message":"Reconcile error: error when getting Pipeline for PipelineRun echo-date-pipeline-run: tekton client cannot get pipeline echo-date-pipeline from local cluster: pipelines.tekton.dev \"echo-date-pipeline\" not found","commit":"1122e76","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"36dddc4d-7bf8-48f4-925f-bf291578206e","knative.dev/key":"default/echo-date-pipeline-run","stacktrace":"github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun.(*Reconciler).ReconcileKind\n\tgithub.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/pipelinerun.go:267\ngithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1/pipelinerun.(*reconcilerImpl).Reconcile\n\tgithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1/pipelinerun/reconciler.go:236\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20250117084104-c43477f0052b/controller/controller.go:540\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20250117084104-c43477f0052b/controller/controller.go:489"}
{"severity":"info","timestamp":"2025-03-27T11:41:20.676Z","logger":"tekton-pipelines-controller.event-broadcaster","caller":"record/event.go:377","message":"Event(v1.ObjectReference{Kind:\"PipelineRun\", Namespace:\"default\", Name:\"echo-date-pipeline-run\", UID:\"0d90692a-32ba-4325-beba-367da1c28dcb\", APIVersion:\"tekton.dev/v1\", ResourceVersion:\"1906\", FieldPath:\"\"}): type: 'Warning' reason: 'Failed' Error retrieving pipeline for pipelinerun default/echo-date-pipeline-run: error when getting Pipeline for PipelineRun echo-date-pipeline-run: tekton client cannot get pipeline echo-date-pipeline from local cluster: pipelines.tekton.dev \"echo-date-pipeline\" not found","commit":"1122e76"}
{"severity":"error","timestamp":"2025-03-27T11:41:20.755Z","logger":"tekton-pipelines-controller","caller":"pipelinerun/reconciler.go:295","message":"Returned an error","commit":"1122e76","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"36dddc4d-7bf8-48f4-925f-bf291578206e","knative.dev/key":"default/echo-date-pipeline-run","targetMethod":"ReconcileKind","error":"1 error occurred:\n\t* error when getting Pipeline for PipelineRun echo-date-pipeline-run: tekton client cannot get pipeline echo-date-pipeline from local cluster: pipelines.tekton.dev \"echo-date-pipeline\" not found\n\n","stacktrace":"github.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1/pipelinerun.(*reconcilerImpl).Reconcile\n\tgithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1/pipelinerun/reconciler.go:295\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20250117084104-c43477f0052b/controller/controller.go:540\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20250117084104-c43477f0052b/controller/controller.go:489"}
{"severity":"error","timestamp":"2025-03-27T11:41:20.755Z","logger":"tekton-pipelines-controller","caller":"controller/controller.go:564","message":"Reconcile error","commit":"1122e76","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"36dddc4d-7bf8-48f4-925f-bf291578206e","knative.dev/key":"default/echo-date-pipeline-run","duration":0.095578902,"error":"1 error occurred:\n\t* error when getting Pipeline for PipelineRun echo-date-pipeline-run: tekton client cannot get pipeline echo-date-pipeline from local cluster: pipelines.tekton.dev \"echo-date-pipeline\" not found\n\n","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20250117084104-c43477f0052b/controller/controller.go:564\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20250117084104-c43477f0052b/controller/controller.go:541\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20250117084104-c43477f0052b/controller/controller.go:489"}
{"severity":"info","timestamp":"2025-03-27T11:41:20.755Z","logger":"tekton-pipelines-controller","caller":"controller/controller.go:548","message":"Reconcile succeeded","commit":"1122e76","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"01658370-9b19-4ddb-b2e7-10647da069c0","knative.dev/key":"default/echo-date-pipeline-run","duration":0.000149079}
{"severity":"info","timestamp":"2025-03-27T11:41:20.755Z","logger":"tekton-pipelines-controller.event-broadcaster","caller":"record/event.go:377","message":"Event(v1.ObjectReference{Kind:\"PipelineRun\", Namespace:\"default\", Name:\"echo-date-pipeline-run\", UID:\"0d90692a-32ba-4325-beba-367da1c28dcb\", APIVersion:\"tekton.dev/v1\", ResourceVersion:\"1906\", FieldPath:\"\"}): type: 'Warning' reason: 'InternalError' 1 error occurred:\n\t* error when getting Pipeline for PipelineRun echo-date-pipeline-run: tekton client cannot get pipeline echo-date-pipeline from local cluster: pipelines.tekton.dev \"echo-date-pipeline\" not found\n\n","commit":"1122e76"}
@rifaterdemsahin ‚ûú /workspaces/PipelineAutomation/6_üî£_Symbols/3_Pipelines (main) $ 

---

It seems like the Tekton client is still unable to retrieve the pipeline. Here are a few additional steps you can take to resolve this issue:

1. **Recreate the Pipeline**:
   Sometimes, recreating the pipeline can resolve issues. Delete the existing pipeline and recreate it using the YAML file:
   ```bash
   kubectl delete pipeline echo-date-pipeline
   kubectl apply -f tekton/pipeline.yaml
   ```

2. **Check Tekton Versions**:
   Ensure that your Tekton CLI (`tkn`) and Tekton Pipelines controller are compatible. You can check the versions with:
   ```bash
   tkn version
   kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'
   ```

3. **Inspect Tekton Controller Logs**:
   Look for any specific error messages in the Tekton controller logs that might indicate the problem:
   ```bash
   kubectl logs -l app=tekton-pipelines-controller -n tekton-pipelines
   ```

4. **Namespace Configuration**:
   Double-check that the namespace configuration in your YAML files matches the namespace where you are deploying the pipeline.

5. **Tekton Community Support**:
   If the issue persists, consider reaching out to the Tekton community for support. You can find help on their [GitHub issues page](https://github.com/tektoncd/pipeline/issues/5804) or [Stack Overflow](https://stackoverflow.com/questions/77690711/tekton-cli-in-pod-cannot-find-existing-pipeline)[1](https://stackoverflow.com/questions/77690711/tekton-cli-in-pod-cannot-find-existing-pipeline)[2](https://github.com/tektoncd/pipeline/issues/5804).

Let me know if you need further assistance or if there's anything else I can help with! üòä


---

It looks like the pipeline was successfully recreated, but the issue persists. Here are a few more steps to try:

1. **Recreate the PipelineRun**:
   Delete the existing PipelineRun and create a new one:
   ```bash
   kubectl delete pipelinerun echo-date-pipeline-run
   kubectl apply -f tekton/pipelinerun.yaml
   ```

2. **Check PipelineRun YAML**:
   Ensure that the PipelineRun YAML file correctly references the `echo-date-pipeline`. Here is an example of what the PipelineRun YAML should look like:
   ```yaml
   apiVersion: tekton.dev/v1beta1
   kind: PipelineRun
   metadata:
     name: echo-date-pipeline-run
   spec:
     pipelineRef:
       name: echo-date-pipeline
     serviceAccountName: default
   ```

3. **Verify Resource Availability**:
   Ensure that all resources required by the pipeline are available and correctly configured.

4. **Tekton Controller Logs**:
   Continue to monitor the Tekton controller logs for any additional errors or warnings:
   ```bash
   kubectl logs -l app=tekton-pipelines-controller -n tekton-pipelines
   ```

5. **Tekton Community Support**:
   If the issue persists, consider reaching out to the Tekton community for support. You can find help on their [GitHub issues page](https://github.com/tektoncd/pipeline/issues/5804) or [Stack Overflow](https://stackoverflow.com/questions/77690711/tekton-cli-in-pod-cannot-find-existing-pipeline)[1](https://stackoverflow.com/questions/77690711/tekton-cli-in-pod-cannot-find-existing-pipeline)[2](https://github.com/tektoncd/pipeline/issues/5804).

Let me know if you need further assistance or if there's anything else I can help with! üòä


---

@rifaterdemsahin ‚ûú /workspaces/PipelineAutomation/6_üî£_Symbols/3_Pipelines (main) $ kubectl logs -l app=tekton-pipelines-controller -n tekton-pipelines
{"severity":"info","timestamp":"2025-03-27T11:37:59.641Z","logger":"tekton-pipelines-controller","caller":"leaderelection/context.go:156","message":"\"tekton-pipelines-controller-59f45c5dcd-48kzn_2805f65e-192f-438a-a560-5b4467225694\" has started leading \"tekton-pipelines-controller.github.com.tektoncd.pipeline.pkg.reconciler.resolutionrequest.reconciler.00-of-01\"","commit":"1122e76"}
{"severity":"info","timestamp":"2025-03-27T11:41:20.662Z","logger":"tekton-pipelines-controller.event-broadcaster","caller":"record/event.go:377","message":"Event(v1.ObjectReference{Kind:\"PipelineRun\", Namespace:\"default\", Name:\"echo-date-pipeline-run\", UID:\"0d90692a-32ba-4325-beba-367da1c28dcb\", APIVersion:\"tekton.dev/v1\", ResourceVersion:\"1906\", FieldPath:\"\"}): type: 'Normal' reason: 'Started' ","commit":"1122e76"}
{"severity":"error","timestamp":"2025-03-27T11:41:20.669Z","logger":"tekton-pipelines-controller","caller":"pipelinerun/pipelinerun.go:438","message":"Failed to determine Pipeline spec to use for pipelinerun echo-date-pipeline-run: error when getting Pipeline for PipelineRun echo-date-pipeline-run: tekton client cannot get pipeline echo-date-pipeline from local cluster: pipelines.tekton.dev \"echo-date-pipeline\" not found","commit":"1122e76","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"36dddc4d-7bf8-48f4-925f-bf291578206e","knative.dev/key":"default/echo-date-pipeline-run","stacktrace":"github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun.(*Reconciler).reconcile\n\tgithub.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/pipelinerun.go:438\ngithub.com/tektoncd/pipeline/pkg/reconciler/pipelinerun.(*Reconciler).ReconcileKind\n\tgithub.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/pipelinerun.go:266\ngithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1/pipelinerun.(*reconcilerImpl).Reconcile\n\tgithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1/pipelinerun/reconciler.go:236\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20250117084104-c43477f0052b/controller/controller.go:540\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20250117084104-c43477f0052b/controller/controller.go:489"}
{"severity":"error","timestamp":"2025-03-27T11:41:20.670Z","logger":"tekton-pipelines-controller","caller":"pipelinerun/pipelinerun.go:267","message":"Reconcile error: error when getting Pipeline for PipelineRun echo-date-pipeline-run: tekton client cannot get pipeline echo-date-pipeline from local cluster: pipelines.tekton.dev \"echo-date-pipeline\" not found","commit":"1122e76","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"36dddc4d-7bf8-48f4-925f-bf291578206e","knative.dev/key":"default/echo-date-pipeline-run","stacktrace":"github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun.(*Reconciler).ReconcileKind\n\tgithub.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/pipelinerun.go:267\ngithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1/pipelinerun.(*reconcilerImpl).Reconcile\n\tgithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1/pipelinerun/reconciler.go:236\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20250117084104-c43477f0052b/controller/controller.go:540\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20250117084104-c43477f0052b/controller/controller.go:489"}
{"severity":"info","timestamp":"2025-03-27T11:41:20.676Z","logger":"tekton-pipelines-controller.event-broadcaster","caller":"record/event.go:377","message":"Event(v1.ObjectReference{Kind:\"PipelineRun\", Namespace:\"default\", Name:\"echo-date-pipeline-run\", UID:\"0d90692a-32ba-4325-beba-367da1c28dcb\", APIVersion:\"tekton.dev/v1\", ResourceVersion:\"1906\", FieldPath:\"\"}): type: 'Warning' reason: 'Failed' Error retrieving pipeline for pipelinerun default/echo-date-pipeline-run: error when getting Pipeline for PipelineRun echo-date-pipeline-run: tekton client cannot get pipeline echo-date-pipeline from local cluster: pipelines.tekton.dev \"echo-date-pipeline\" not found","commit":"1122e76"}
{"severity":"error","timestamp":"2025-03-27T11:41:20.755Z","logger":"tekton-pipelines-controller","caller":"pipelinerun/reconciler.go:295","message":"Returned an error","commit":"1122e76","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"36dddc4d-7bf8-48f4-925f-bf291578206e","knative.dev/key":"default/echo-date-pipeline-run","targetMethod":"ReconcileKind","error":"1 error occurred:\n\t* error when getting Pipeline for PipelineRun echo-date-pipeline-run: tekton client cannot get pipeline echo-date-pipeline from local cluster: pipelines.tekton.dev \"echo-date-pipeline\" not found\n\n","stacktrace":"github.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1/pipelinerun.(*reconcilerImpl).Reconcile\n\tgithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1/pipelinerun/reconciler.go:295\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20250117084104-c43477f0052b/controller/controller.go:540\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20250117084104-c43477f0052b/controller/controller.go:489"}
{"severity":"error","timestamp":"2025-03-27T11:41:20.755Z","logger":"tekton-pipelines-controller","caller":"controller/controller.go:564","message":"Reconcile error","commit":"1122e76","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"36dddc4d-7bf8-48f4-925f-bf291578206e","knative.dev/key":"default/echo-date-pipeline-run","duration":0.095578902,"error":"1 error occurred:\n\t* error when getting Pipeline for PipelineRun echo-date-pipeline-run: tekton client cannot get pipeline echo-date-pipeline from local cluster: pipelines.tekton.dev \"echo-date-pipeline\" not found\n\n","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20250117084104-c43477f0052b/controller/controller.go:564\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20250117084104-c43477f0052b/controller/controller.go:541\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20250117084104-c43477f0052b/controller/controller.go:489"}
{"severity":"info","timestamp":"2025-03-27T11:41:20.755Z","logger":"tekton-pipelines-controller","caller":"controller/controller.go:548","message":"Reconcile succeeded","commit":"1122e76","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"01658370-9b19-4ddb-b2e7-10647da069c0","knative.dev/key":"default/echo-date-pipeline-run","duration":0.000149079}
{"severity":"info","timestamp":"2025-03-27T11:41:20.755Z","logger":"tekton-pipelines-controller.event-broadcaster","caller":"record/event.go:377","message":"Event(v1.ObjectReference{Kind:\"PipelineRun\", Namespace:\"default\", Name:\"echo-date-pipeline-run\", UID:\"0d90692a-32ba-4325-beba-367da1c28dcb\", APIVersion:\"tekton.dev/v1\", ResourceVersion:\"1906\", FieldPath:\"\"}): type: 'Warning' reason: 'InternalError' 1 error occurred:\n\t* error when getting Pipeline for PipelineRun echo-date-pipeline-run: tekton client cannot get pipeline echo-date-pipeline from local cluster: pipelines.tekton.dev \"echo-date-pipeline\" not found\n\n","commit":"1122e76"}
{"severity":"info","timestamp":"2025-03-27T12:02:44.296Z","logger":"tekton-pipelines-controller","caller":"controller/controller.go:548","message":"Reconcile succeeded","commit":"1122e76","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"f71eee35-7fd9-4529-8c38-c32863f97f9d","knative.dev/key":"default/echo-date-pipeline-run","duration":0.000140993}
@rifaterdemsahin ‚ûú /workspaces/PipelineAutomation/6_üî£_Symbols/3_Pipelines (main) $ 

---

It looks like the Tekton client is still unable to find the `echo-date-pipeline`. Here are a few more steps to try:

1. **Recreate the PipelineRun**:
   Delete the existing PipelineRun and create a new one:
   ```bash
   kubectl delete pipelinerun echo-date-pipeline-run
   kubectl apply -f tekton/pipelinerun.yaml
   ```

2. **Check PipelineRun YAML**:
   Ensure that the PipelineRun YAML file correctly references the `echo-date-pipeline`. Here is an example of what the PipelineRun YAML should look like:
   ```yaml
   apiVersion: tekton.dev/v1beta1
   kind: PipelineRun
   metadata:
     name: echo-date-pipeline-run
   spec:
     pipelineRef:
       name: echo-date-pipeline
     serviceAccountName: default
   ```

3. **Verify Resource Availability**:
   Ensure that all resources required by the pipeline are available and correctly configured.

4. **Tekton Controller Logs**:
   Continue to monitor the Tekton controller logs for any additional errors or warnings:
   ```bash
   kubectl logs -l app=tekton-pipelines-controller -n tekton-pipelines
   ```

5. **Tekton Community Support**:
   If the issue persists, consider reaching out to the Tekton community for support. You can find help on their [GitHub issues page](https://github.com/tektoncd/pipeline/issues/5804) or [Stack Overflow](https://stackoverflow.com/questions/77690711/tekton-cli-in-pod-cannot-find-existing-pipeline)[1](https://stackoverflow.com/questions/77690711/tekton-cli-in-pod-cannot-find-existing-pipeline)[2](https://github.com/tektoncd/pipeline/issues/5804).

Let me know if you need further assistance or if there's anything else I can help with! üòä